name: arif
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0-45.0.dev <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  flutter_easyloading: ^3.0.3
  flutter_spinkit: ^5.1.0
  flutter: 
    sdk: flutter
  advance_pdf_viewer: ^2.0.1
  video_player: ^2.2.7
  chewie: ^1.2.2
  photo_view: ^0.13.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    -
  fonts:
    - family: Changa Regular
      fonts:
        - asset: assets/fonts/changa_regular.ttf